namespace: sample

deployment:
  enabled: true

app:
  name: sample
  port: 80
  targetPort: 80
  service:
    type: NodePort
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests: 
      cpu: 100m
      memory: 128Mi
  volumeMounts:
    - name: sample-volume
      mountPath: /sample/sample.json
      subPath: sample.json
  volumes:
    - name: sample-volume
      configMap:
        name: sample-cm
  configReload:
    enabled: true

configMap:
  name: sample-cm

image:
  name: sample.acer.com/sample
  pullPolicy: Always
  tag: latest

ingress:
  enabled: false
  name: sample-ingress
  secretName: sample-tls
  hostname: sample.intra.acer.com
  crt: xxx
  key: xxx


cronjob:
  enabled: false
  schedule: "0 0 * * *"
  image:
    name: sample.acer.com/sample-cronjob
    tag: latest
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests: 
      cpu: 100m
      memory: 128Mi
  volumeMounts:
    - name: sample-cronjob-volume
      mountPath: /sample/sample.json
      subPath: sample.json
  volumes:
    - name: sample-cronjob-volume
      configMap:
        name: sample-cm