namespace: sample

deployments:
  - name: sample1
    enabled: true
    image:
      name: sample.acer.com/sample
      pullPolicy: Always
      tag: latest
    port: 80
    targetPort: 80
    service:
      type: NodePort
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests: 
        cpu: 100m
        memory: 128Mi
    useVolume: true
    volumeMounts:
      - name: sample1-volume
        mountPath: /sample/sample1.json
        subPath: sample1.json
    volumes:
      - name: sample1-volume
        configMap:
          name: sample1-cm
    configReload:
      enabled: true

  - name: sample2
    enabled: true
    image:
      name: sample.acer.com/sample2
      pullPolicy: Always
      tag: latest
    port: 81
    targetPort: 81
    service:
      type: NodePort
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests: 
        cpu: 100m
        memory: 128Mi
    useVolume: false
    env:
      - name: SAMPLE_ENV_VAR
        value: "sample-value"
    configReload:
      enabled: true


configMap:
  name: sample-cm

ingress:
  enabled: false
  name: sample-ingress
  secretName: sample-tls
  hostname: sample.intra.acer.com
  crt: xxx
  key: xxx

cronjobs:
  - name: sample1-cronjob
    enabled: true
    schedule: "0 0 * * *"
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    image:
      name: sample.acer.com/sample1-cronjob
      tag: latest
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests: 
        cpu: 100m
        memory: 128Mi
    useVolume: true
    volumeMounts:
      - name: sample-cronjob-volume
        mountPath: /sample/sample.json
        subPath: sample.json
    volumes:
      - name: sample-cronjob-volume
        configMap:
          name: sample-cm

  - name: sample2-cronjob
    enabled: true
    schedule: "0 1 * 2 *"
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    image:
      name: sample.acer.com/sample2-cronjob
      tag: latest
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests: 
        cpu: 100m
        memory: 128Mi
    useVolume: false
    env:
      - name: SAMPLE_ENV_VAR1
        value: "sample-cronjob-value1"