namespace: sample

### Deployments
### Define deployment arguments
deployments:
  - name: sample1
    enabled: true
    image:
      name: example.com/sample
      pullPolicy: Always
      tag: latest
    port: 80
    targetPort: 80
    service:
      type: NodePort
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests: 
        cpu: 100m
        memory: 128Mi
    useVolume: true
    volumeMounts:
      - name: sample1-volume
        mountPath: /sample/sample1.json
        subPath: sample1.json
    volumes:
      - name: sample1-volume
        configMap:
          name: sample1-cm
    configReload:
      enabled: true

  - name: sample2
    enabled: true
    image:
      name: example.com/sample2
      pullPolicy: Always
      tag: latest
    port: 81
    targetPort: 81
    service:
      type: NodePort
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests: 
        cpu: 100m
        memory: 128Mi
    useVolume: false
    env:
      - name: SAMPLE_ENV_VAR
        value: "sample-value"
    configReload:
      enabled: true


configMap:
  name: sample-cm


ingress:
  enabled: true
  crt: xxx
  key: xxx
  name: sample-ingress
  secretName: sample-tls
  hosts:
    - hostname: sample.example.com
      paths:
        - path: /
          backend:
            serviceName: sample1-svc
        - path: /api
          backend:
            serviceName: sample2-svc
    - hostname: another-sample.example.com
      paths:
        - path: /
          backend:
            serviceName: sample1-svc


cronjobs:
  - name: sample1-cronjob
    enabled: true
    schedule: "0 0 * * *"
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    image:
      name: example.com/sample1-cronjob
      tag: latest
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests: 
        cpu: 100m
        memory: 128Mi
    useVolume: true
    volumeMounts:
      - name: sample-cronjob-volume
        mountPath: /sample/sample.json
        subPath: sample.json
    volumes:
      - name: sample-cronjob-volume
        configMap:
          name: sample-cm

  - name: sample2-cronjob
    enabled: false
    schedule: "0 1 * 2 *"
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    image:
      name: example.com/sample2-cronjob
      tag: latest
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests: 
        cpu: 100m
        memory: 128Mi
    useVolume: false
    env:
      - name: SAMPLE_ENV_VAR1
        value: "sample-cronjob-value1"