apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
{{- $files := .Files.Glob "conf/*" }}
{{- range $path, $_ := $files }}
  {{ $name := base $path }}
  {{ $name }}: |
{{ $.Files.Get $path | nindent 4 }}
{{- end }}