{{- range .Values.cronjobs }}
{{- if .enabled }}
---
apiVersion: betch/v1
kind: CronJob
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .name }}
spec:
  schedule: {{ .schedule }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .name }}
              image: "{{ .image.name }}:{{ .image.tag }}"
              resources:
                limits:
                  cpu: {{ .resources.limits.cpu }}
                  memory: {{ .resources.limits.memory }}
                requests:
                  cpu: {{ .resources.requests.cpu }}
                  memory: {{ .resources.requests.memory }}
              restartPolicy: {{ .restartPolicy }}
              {{- if .useVolume }}
              volumeMounts: {{ toYaml .volumeMounts | nindent 16 }}
              {{- end }}
              {{- if .env }}
              env: {{ toYaml .env | nindent 16 }}
              {{- end }}
          {{- if .useVolume }}
          volumes: {{ toYaml .volumes | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}