{{- range .Values.deployments }}
{{- if .enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .name }}
  annotations:
    {{- if .configReload.enabled }}
    reloader.stakater.com/auto: "true"
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
    template:
      metadata:
      labels:
        app: {{ .name }}
      spec:
        containers:
        - name: {{ .name }}
          image: "{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          resources:
            limits:
              cpu: {{ .resources.limits.cpu }}
              memory: {{ .resources.limits.memory }}
            requests:
              cpu: {{ .resources.requests.cpu }}
              memory: {{ .resources.requests.memory }}
          ports:
            - containerPort: {{ .port }}
          {{- if .useVolume }}
          volumeMounts: {{ toYaml .volumeMounts | nindent 12 }}
          {{- else }}
          env: {{ toYaml .env | nindent 12 }}
          {{- end }}
      {{- if .useVolume }}
      volumes: {{ toYaml .volumes | nindent 10 }}
      {{- end }}
{{- end }}
{{- end }}
