{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: {{ range $index, $element := .Values.ingress.hosts }}{{ if $index }},{{ end }}{{ $element.hostname }}{{ end }}
    external-dns.alpha.kubernetes.io/ttl: "1"
spec:
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
      - {{ .hostname }}
      {{- end }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    {{- range .Values.ingress.hosts }}
  - host: {{ .hostname }}
    http:
      paths:
        {{- range .paths }}
        - path: {{ .path }}
          pathType: Prefix
          backend:
            service:
              name: {{ .backend.serviceName }}
              port:
                number: {{ $backendServiceName := .backend.serviceName | replace "-svc" "" }}{{ range $.Values.deployments }}{{ if eq .name $backendServiceName }}{{ .port }}{{ end }}{{ end }}
        {{- end }}
    {{- end }}
{{- end }}
