{{ if .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.secretName }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.crt }}
  tls.key: {{ .Values.ingress.key }}
{{ end }}