apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
{{- if .Values.ingress.enabled }}
  type: ClusterIP
{{- else }}
  type: {{ .Values.app.service.type }}
{{- end }}
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.targetPort }}