{{- range .Values.deployments }}
{{- if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-svc
  namespace: {{ $.Values.namespace }}
spec:
{{- if $.Values.ingress.enabled }}
  type: CluterIP
{{- else }}
  type: {{ .service.type }}
{{- end }}
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
{{- end }}